spring:
  application:
    name: Operation Clean Sweep
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE:test}
      authentication-database: admin
